name: Build TWRP

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Dhaka  # Set timezone to your region
      ALLOW_MISSING_DEPENDENCIES: true

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev
        
    - name: Sync TWRP sources
      run: |
        mkdir -p ~/twrp
        cd ~/twrp
        repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-12.1
        repo sync

    - name: Copy device tree to source
      run: |
        cd ~/twrp
        mkdir -p device/symphony/z60plus
        cp -r ${{ github.workspace }}/* device/symphony/z60plus/

    - name: Build TWRP recovery image
      run: |
        cd ~/twrp
        source build/envsetup.sh
        lunch omni_z60plus-eng
        mka recoveryimage

    - name: Upload recovery image
      uses: actions/upload-artifact@v3
      with:
        name: TWRP-Recovery
        path: ~/twrp/out/target/product/z60plus/recovery.img
